function Fx = hamilton_x_limit_cycle(C,E0,h,px,px_,py,py_,x,x_,y,y_)
%HAMILTON_X_LIMIT_CYCLE
%    FX = HAMILTON_X_LIMIT_CYCLE(C,E0,H,PX,PX_,PY,PY_,X,X_,Y,Y_)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    24-Aug-2024 15:44:53

t2 = E0.*2.0;
t3 = x./2.0;
t4 = x_./2.0;
t5 = y./2.0;
t6 = y_./2.0;
t7 = t3+t4;
t8 = t5+t6;
t9 = t7.^2;
t10 = t8.^2;
t11 = t9+t10-1.0;
t12 = t7.*t11;
t13 = t8.*t11;
t14 = -t12;
t15 = t7+t13;
t16 = t15.^2;
t17 = t8+t14;
t18 = t17.^2;
t19 = t2+t16+t18;
t20 = 1.0./sqrt(t19);
Fx = [-x+x_+C.*h.*t20.*(px./2.0+px_./2.0+t17);-y+y_+C.*h.*t20.*(py./2.0+py_./2.0-t15)];
