function Fp = hamilton_p_limit_cycle(C,E0,h,px,px_,py,py_,x,x_,y,y_)
%HAMILTON_P_LIMIT_CYCLE
%    FP = HAMILTON_P_LIMIT_CYCLE(C,E0,H,PX,PX_,PY,PY_,X,X_,Y,Y_)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    24-Aug-2024 15:44:54

t2 = E0.*2.0;
t3 = px./2.0;
t4 = px_./2.0;
t5 = py./2.0;
t6 = py_./2.0;
t7 = x./2.0;
t8 = x_./2.0;
t9 = y./2.0;
t10 = y_./2.0;
t11 = t7+t8;
t12 = t9+t10;
t13 = t3+t4;
t14 = t5+t6;
t15 = t11.^2;
t16 = t12.^2;
t17 = t11.*t12.*2.0;
t18 = t15+t16-1.0;
t19 = t11.*t18;
t20 = t12.*t18;
t21 = -t19;
t22 = t11+t20;
t23 = t22.^2;
t24 = t12+t21;
t25 = t24.^2;
t26 = t2+t23+t25;
t27 = 1.0./sqrt(t26);
Fp = [-px+px_+C.*h.*t27.*(t13.*(t15.*2.0+t18)+t14.*(t17+1.0));-py+py_+C.*h.*t27.*(t14.*(t16.*2.0+t18)+t13.*(t17-1.0))];
