function Jx = jacobian_x_limit_cycle(C,E0,h,px,px_,py,py_,x,x_,y,y_)
%JACOBIAN_X_LIMIT_CYCLE
%    JX = JACOBIAN_X_LIMIT_CYCLE(C,E0,H,PX,PX_,PY,PY_,X,X_,Y,Y_)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    24-Aug-2024 15:44:53

t2 = E0.*2.0;
t3 = px./2.0;
t4 = px_./2.0;
t5 = py./2.0;
t6 = py_./2.0;
t7 = x./2.0;
t8 = x_./2.0;
t9 = y./2.0;
t10 = y_./2.0;
t11 = -t5;
t12 = -t6;
t13 = t7+t8;
t14 = t9+t10;
t15 = t13.^2;
t16 = t14.^2;
t21 = t13.*t14;
t17 = t15./2.0;
t18 = t15.*(3.0./2.0);
t19 = t16./2.0;
t20 = t16.*(3.0./2.0);
t22 = t21+1.0./2.0;
t23 = t21-1.0./2.0;
t24 = t15+t16-1.0;
t25 = t17+t20-1.0./2.0;
t26 = t18+t19-1.0./2.0;
t27 = t13.*t24;
t28 = t14.*t24;
t29 = -t27;
t30 = t13+t28;
t31 = t30.^2;
t32 = t14+t29;
t35 = t11+t12+t30;
t36 = t22.*t30.*2.0;
t40 = t25.*t30.*2.0;
t33 = t32.^2;
t34 = t3+t4+t32;
t37 = -t36;
t38 = t23.*t32.*2.0;
t41 = t26.*t32.*2.0;
t39 = -t38;
t42 = t2+t31+t33;
t45 = t37+t41;
t43 = 1.0./sqrt(t42);
t46 = t39+t40;
t44 = t43.^3;
Jx = reshape([-C.*h.*t26.*t43-(C.*h.*t34.*t44.*(t36-t41))./2.0-1.0,-C.*h.*t22.*t43+(C.*h.*t35.*t44.*(t36-t41))./2.0,-C.*h.*t23.*t43+(C.*h.*t34.*t44.*(t38-t40))./2.0,-C.*h.*t25.*t43-(C.*h.*t35.*t44.*(t38-t40))./2.0-1.0],[2,2]);
