function Jp = jacobian_p_limit_cycle(C,E0,h,x,x_,y,y_)
%JACOBIAN_P_LIMIT_CYCLE
%    JP = JACOBIAN_P_LIMIT_CYCLE(C,E0,H,X,X_,Y,Y_)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    24-Aug-2024 15:44:54

t2 = E0.*2.0;
t3 = x./2.0;
t4 = x_./2.0;
t5 = y./2.0;
t6 = y_./2.0;
t7 = t3+t4;
t8 = t5+t6;
t9 = t7.^2;
t10 = t8.^2;
t11 = t7.*t8;
t12 = t9+t10-1.0;
t13 = t7.*t12;
t14 = t8.*t12;
t15 = -t13;
t16 = t7+t14;
t17 = t16.^2;
t18 = t8+t15;
t19 = t18.^2;
t20 = t2+t17+t19;
t21 = 1.0./sqrt(t20);
Jp = reshape([C.*h.*t21.*(t9.*(3.0./2.0)+t10./2.0-1.0./2.0)-1.0,C.*h.*t21.*(t11-1.0./2.0),C.*h.*t21.*(t11+1.0./2.0),C.*h.*t21.*(t9./2.0+t10.*(3.0./2.0)-1.0./2.0)-1.0],[2,2]);
